profile: cover.out

local-prefix: github.com/hluk/retasc-konflux-test

threshold:
  # The minimum coverage that each file should have
  file: 85
  # The minimum coverage that each package should have
  package: 85
  # The minimum total coverage project should have
  total: 85

exclude:
  paths:
    - ^docs/
