kind: Deployment
apiVersion: apps/v1
metadata:
  name: retasc-konflux-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retasc-konflux-test
  template:
    metadata:
      labels:
        app: retasc-konflux-test
    spec:
      containers:
        - name: retasc-konflux-test
          image: retasc-konflux-test:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: retasc-konflux-test
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: retasc-konflux-test
