name: go-test-coverage
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  gotest:
    runs-on: ubuntu-latest

    permissions:
      # Allow updating coverage badges
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.20.x

      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
          ## when token is not specified (value '') this feature is turned off
          ## in this example badge is created and committed only for main brach
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          ## name of branch where badges are stored
          git-branch: badges
